[workspace]
resolver = "3"
members = [
    "crates/vxcc-ir",
    "crates/vxcc-type-parser",
    "crates/vxcc-type-parser-proc",
    "crates/vxcc-dialect-parser"
, "crates/vxcc-base-dialect", "crates/vxcc-num-dialect"]
